language: cpp

matrix:
  include:
    # gcc-5 (Ubuntu)
    - env: GCC_VERSION=5
      compiler: gcc
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test
    # clang-3.5 (Ubuntu)
    - env: CLANG_VERSION=3.5
      compiler: clang
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - clang-3.5
            - libc++-dev
          sources:
            - ubuntu-toolchain-r-test
    # clang-3.6 (Ubuntu)
    - env: CLANG_VERSION=3.6
      compiler: clang
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - clang-3.6
            - libc++-dev
          sources:
            - ubuntu-toolchain-r-test

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi
  - if [ -n "${BEFORE_INSTALL}" ]; then ${BEFORE_INSTALL}; fi
  - if [ -n "$GCC_VERSION" ]; then export CC="gcc-${GCC_VERSION}" CXX="g++-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}" CXXFLAGS="-stdlib=libc++"; fi

install:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

script:
  - ctest -VV

notifications:
  email: false